version: '3.5'
services: 
  reppydatabase:
    container_name: reppydatabase
    environment:
      MYSQL_DATABASE: 'reppy'
      MYSQL_USER: 'reppy'
      MYSQL_PASSWORD: 'userpassword'
      MYSQL_ROOT_PASSWORD: 'adminpassword'
    image: mysql:5.7
    volumes:
      - data:/var/lib/mysql:rw
    ports:
      - 33060:3306
    restart: always
volumes:
  data: